name: Build NOMIX Pro Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build Standalone with Nuitka
        run: python -m nuitka main.py --standalone --assume-yes-for-downloads --windows-icon-from-ico=assets/icon.ico --windows-console-mode=force --enable-plugin=anti-bloat --output-dir=build_output --output-filename=NOMIX_CLONER.exe

      - name: Compile Installer with Inno Setup
  shell: pwsh
  run: |
    & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "setup.iss"

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NOMIX-Pro-Installer
          path: Output\NOMIX_V3_Installer.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Output/NOMIX_V3_Installer.exe
          name: NOMIX CLONER ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
